#
# SQL Export
# Created by Querious (201026)
# Created: May 23, 2018 at 15:11:52 GMT-4
# Encoding: Unicode (UTF-8)
#


CREATE DATABASE IF NOT EXISTS `kube_test` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
USE `kube_test`;




SET @PREVIOUS_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;


DROP TABLE IF EXISTS `access`;


CREATE TABLE `access` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `from` varchar(128) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;




SET FOREIGN_KEY_CHECKS = @PREVIOUS_FOREIGN_KEY_CHECKS;


SET @PREVIOUS_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;


LOCK TABLES `access` WRITE;
TRUNCATE `access`;
ALTER TABLE `access` DISABLE KEYS;
INSERT INTO `access` (`id`, `from`, `date`) VALUES 
	(6,'::1','2018-05-23 15:11:05'),
	(7,'::1','2018-05-23 15:11:06');
ALTER TABLE `access` ENABLE KEYS;
UNLOCK TABLES;




SET FOREIGN_KEY_CHECKS = @PREVIOUS_FOREIGN_KEY_CHECKS;


