version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t   nullah/kubetest:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push nullah/kubetest:$TAG

